### PR TITLE
Fix "0f" causing Voxy programs failing to compile

### LINKED ISSUE #593: Photonics support PR breaks Voxy Compat
### What happened?

Latest photon-main has broken Voxy compatibility and after `git bisect` I figure out what breaks that:
```
git bisect good a1c74d44d615079795daae8fe50932c132ee4358
62387de6f9b6af7f84ce57f5036d073ce999a322 is the first bad commit
commit 62387de6f9b6af7f84ce57f5036d073ce999a322
Author: Essentuan <51426319+Essentuan@users.noreply.github.com>
Date:   Sat Apr 25 14:00:18 2026 -0500

    Add support for Photonics (#563)
```
DH support is fine, and the bisect is done w/o photonics.

### Minecraft Version

1.21.11

### Which shader mod are you using?

Iris

### Shader mod version

1.10.7

### Shader settings

```conf
default, no setting file
```

### Relevant log output

```text
https://mclo.gs/QOgxfj4
[14:10:35] [Render thread/ERROR]: [me.cx.vy.ct.ce.rg.sn.bd.AbstractSectionRenderer]: Failed to compile shader patch, using normal pipeline to prevent errors java.lang.RuntimeException: Shader compilation failed of type FRAGMENT, see log for details, dumped shader
java.lang.RuntimeException: Shader compilation failed of type FRAGMENT, see log for details, dumped shader
```

### PR DESCRIPTION
**Pull request by rrtt217**
Fix #593.
GLSL specification do not allow `0f` as a floating point value as it do not have either decimal point or exponent part , use `0.0f` instead.

### CODE REVIEW

**Comment by sixthsurge** [comment]
Thank you!
